### ISSUE TITLE
NPM install fails from version 0.0.15

### ISSUE THREAD

**Issue by Parthipan-Natkunam** [m3o/m3o-node#6]
command run:
`npm install --save @m3o/m3o-node`

Error:
```bash
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @m3o/m3o-node@0.0.19 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @m3o/m3o-node@0.0.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Observation:
install command works properly  and succeeds on `version 0.0.14`

Speculation:
Might have something to do with the install script that has been added in `package.json` since `v0.0.15`

Temporary workaround followed:
Downgraded to v 0.0.14 installation with `npm install --save @m3o/m3o-node@0.0.14`

**Comment by martinv678** [comment]
Hello, if you try version `0.0.19` it should work okay. Have you tried removing your `node_modules` and trying again?

**Comment by Parthipan-Natkunam** [comment]
@martinv678 tested version `0.0.24`. This works. Thanks for resolving this.
